### ISSUE TITLE
Define/add more indices for our models

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1169]
Currently our database models do define very few indices. We should examine them closely and add indices for columns that are used in filter/sorting operations.

E.g. `opgengever.ogds.models.User` does not define indices for `firstname` and `lastname` columns, but these columns are used for sorting results.

**Comment by lukasgraf** [comment]
Also note that in Oracle, the presence of indexes an directly affect whether row-level locks can be used, or table-level locks need to be issued:

> **Locking and foreign key indexes**
>
> Without an index on the child table's foreign key, **table-level locking may occur** when a parent row is updated.  Rampant author Jeff Hunter notes that there is a table-level locking issue prior to release 11g:

http://www.dba-oracle.com/t_foreign_key_indexing.htm

---

> **Deadlocks**
>
> Deadlocks occur when two people hold a resource that the other wants. Oracle records all deadlocks in a trace file. **The number one cause of deadlocks is un-indexed foreign keys**

http://www.datadisk.co.uk/html_docs/oracle/locking.htm

**Comment by lukasgraf** [comment]
Additionally, we should examine if we have a significant performance loss anywhere because of the ["n+1 selects issue"](http://docs.sqlalchemy.org/en/latest/orm/loading_relationships.html). Some of our deployments talk to Oracle over the network, which can have a drastic impact in such cases. SQLAlchemy offers fine grained control over [relationship loading](http://docs.sqlalchemy.org/en/latest/orm/loading_relationships.html), so we could possibly benefit from using eager loading in some places.

**Comment by deiferni** [comment]
this has been open for >3 years. we always bump it to the next release. -> close.
