### ISSUE TITLE
Find and shorten task titles > 255 characters

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1217]
The length for `Task.title` has been limited in the SQL model to 255 characters. However, the `zope.schema` model on the Plone side isn't limited yet. So we need to find thats whose title is too long and shorten that title to 255 characters or less.

**Comment by deiferni** [comment]
Maybe this has been resolved. double check.

**Comment by maethu** [comment]
@deiferni This was fixed by yourself in https://github.com/4teamwork/opengever.core/commit/dca0834e63781e4ce16f28636231b37b3d0b832d (Release 4.6.0) 

But 256 characters are allowed.
It's finde since the sql field can contain 256 characters.
Anything longer would raise: `value too long for type character varying(256)`

I updated the given test case slightly in 4cd3bbba5bafeea71f5e01b749e1053fd17ea49e

I also added a upgrade step to shorten too long titles: 0993a1ab5bdd8100fc66447c80f2a219fbfe7425

**Comment by lukasgraf** [comment]
@deiferni @maethu actually, in MySQL the maximum length for a `VARCHAR` column (when using the `utf8mb4` character set) is **255 characters, not 256**.

**Comment by deiferni** [comment]
@lukasgraf but then that would affect all our sql models, right?

**Comment by lukasgraf** [comment]
@deiferni indeed. Which is why we introduced these length constants back in the day, to unify handling of column lengths in SQL models: https://github.com/4teamwork/opengever.ogds.models/blob/master/opengever/ogds/models/__init__.py#L4-L10

(If that's what you meant, but maybe I didn't quite understand your question)
