### ISSUE TITLE
"&"-Zeichen wird bei Übertrag in Protokoll entfernt

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#2202]
Wird ein "&"-Zeichen in der SPV eingesetzt, wird dieses nicht mit ins Protokoll geschickt.
siehe: https://lab.onegovgever.ch/sitzungen/committee-48/meeting-87/protocol 
![bildschirmfoto 2016-09-29 um 16 49 38](https://cloud.githubusercontent.com/assets/20790360/18959073/26353df2-8665-11e6-9843-0d2223cbfc2f.png)
![bildschirmfoto 2016-09-29 um 16 49 25](https://cloud.githubusercontent.com/assets/20790360/18959072/2635347e-8665-11e6-95e0-e4fa2fd3a0f4.png)

**Comment by deiferni** [comment]
Turns out this is not as simple as we thought initially, sablon seems to drop `&amp;` when creating the word xmls. The gever side seems to handle everything correctly.

Since it is currently unclear whether we still want to use the sablon approach in the future i'll move this issue to the next release.

**Comment by elioschmutz** [comment]
@deiferni what is the decision of this issue? Do we want to use sablon in the future or not?

**Comment by deiferni** [comment]
We're gonna move away from creating the protocol in a web-form. I'll close.
