### ISSUE TITLE
Differ between address and greeting salutation

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2820]
**Use case** 
It should be possible to differ between an address and an greetings salutation when defining the salutation of a contact. 
Especially when using contactsmetadata as docproperties in doc templates, like the following letter template:
![bildschirmfoto_2017-04-04_um_17_45_26](https://cloud.githubusercontent.com/assets/485755/24665726/919c88a2-195e-11e7-9c09-da4926653f66.png)

**Planed Solution**
Extracting and normalizing the salutation into a separate table which contains an `address_salutation` and a `greetings_salutation` column.

![bildschirmfoto 2017-04-04 um 17 41 26](https://cloud.githubusercontent.com/assets/485755/24667670/8e102af8-1964-11e7-9895-6316bf02e300.png)

Replacing the docproperty `ogg.recipient.person.salutation` with two properties `ogg.recipient.person.address_salutation` and `ogg.recipient.person.greeting_salutation`.
There is now option for placeholders in the salutation planned yet, so the salutation property will only contains the value `Sehr geehrter Herr` and not `Sehr geehrter Herr Muster`.

An Add or edit form is currently not necessary, because the contacts modul is read-only for the moment.

**Comment by phgross** [comment]
@lukasgraf @deiferni any suggestions?

**Comment by deiferni** [comment]
cardinality: the arrows in the model are a bit unclear 🤔, but it should be defined that `person` has `0..1` `salutation` and `salutation` has `0..n` `persons`.
nullability: `address_salutation` non-nullable, `greeting_salutation` nullable?

also since naming is important i did google a little more 😉 

the short one (Mr., Ms.) also seems to be called `title` or `form of address` (http://www.linguee.de/deutsch-englisch/uebersetzung/anrede+herr+frau.html) 

the long one (Dear ...) seems to be called `opening` or `greeting`

So if you want you could could rename to:

**salutation**
- form_of_address (former address_salutation)
- greeting (former greeting_salutation)

**Comment by phgross** [comment]
Die Anforderung ist zurzeit nicht mehr aktuell, ich schliesse diesen Issue.
