### ISSUE TITLE
Proposals: have less packages in auto-checkout and move versions

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#3084]
At the moment, dependency packages are often added to the auto-checkout-list in `opengever.core` and kept there until right before `opengever.core` is released.

- While dependencies are in the auto-checkout-list it is unclear what exactly we require (feature, version), since we have no pinnings (versions, git commits). We used to add comments for tracking that, but we stopped doing that at some point.
- Things may change in the dependency, breaking `opengever.core` and it is sometimes hard to find out what happened. When it happens, nobody is responsible.
- When switching branches in the `sources.cfg`, a simple `bin/buildout` will not be enough since `mr.developer` does not switch branches.

I think we should change the "definition of done" of a PR to include doing necessary releases of dependency. I think releasing of an `ftw.*`-package is not the job of the opengever release manager but of the developer submitting the patch.
The auto-checkout feature is great for development: the dev can track the external changes and the CI can build. But `master` is a stable branch, it should have a short list of auto-checkouts.

Proposal:
- cleanup the auto-checkout list in `master`
- no longer merge pull requests which add dependencies to `auto-checkout`
- we will need to make exceptions for convenience.

@4teamwork/gever thoughts and opinions?

**Comment by lukasgraf** [comment]
@jone I fully agree! 👍

**Comment by deiferni** [comment]
i second 👍 

if we start going that way we also should discuss what to do with kgs.4teamwork.ch/release/opengever/develop.

at the moment we usually want to update the kgs pinnings while developing, since our source-checkouts don't include `https://raw.githubusercontent.com/4teamwork/opengever.core/master/versions.cfg`. but since those development pinnings are in a separate repository this always requires some "timing" (update kgs develop pinnings, trigger build, merge into master) which in the worst case may lead to a situation where only the to-be-merged branch will pass against the kgs pinnings but not master.

i would propose to eliminate the separate development pinnings in the kgs repository and only rely on `versions.cfg` for development/source pinnings. for the pinnings that did not change we could start using the latest symlink http://kgs.4teamwork.ch/release/opengever/latest again. this would allow us to directly couple pinning changes to a pull-request, and also guarantee that all source checkouts use the same pinnings as `master`.

proposed amendment to proposal:
- eliminate https://github.com/4teamwork/kgs/blob/master/release/opengever/develop
- keep development pinnings in https://github.com/4teamwork/opengever.core/blob/master/versions.cfg
- let https://github.com/4teamwork/gever-buildouts/blob/master/source-master.cfg inherit from http://kgs.4teamwork.ch/release/opengever/latest and https://raw.githubusercontent.com/4teamwork/opengever.core/master/versions.cfg

**Comment by jone** [comment]
+1 for eliminating the develop-kgs and using `versions.cfg` of `opengever.core`!
I would probably commit the gever-version to `opengever.core`'s `versions.cfg`, e.g.:
```
[buildout]
extends =
    http://kgs.4teamwork.ch/release/opengever/2017.2.4
```
The reason for hard-coding that is that a half-year old branch would be still buildable (CI) with the gever-version it was built against.

Are there a lot of places where the `develop`-kgs is in use? Should we extend the master versions.cfg then for not destrying everything?

Should I make PRs?

**Comment by phgross** [comment]
Sounds reasonable for me. 

But I would add `plonetheme.teamraum` permanently to the development-package.

**Comment by jone** [comment]
**Do we ever need a "latest" version (!= master)?**

We also discussed that we could get rid of the kgs completely and solely use github for getting the versions once we've moved versions to gever core.

A deployment could then use:
```
[buildout]
extends =
    ...
    https://raw.githubusercontent.com/4teamwork/opengever.core/2017.2.5/versions.cfg
```
But it would be hard to have a "latest" version, which points to the latest tag, since we cannot use symlinks for tags.

**Comment by deiferni** [comment]
the only use-case for having the latest symlink that comes to my mind is what i described above. but now that we move all pinnings to versions.cfg that use-case is no longer a thing. i'd say we don't need the `latest` symlink any more (or we won't start using it again, since afaik it is unused now).
