### ISSUE TITLE
OGIP 39 - PDF speichern unter

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4214]
Platzhalter Issue für [OGIP 39](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-2578/document-23463#overview)

**Comment by deiferni** [comment]
Auch relevant für https://basecamp.com/2768704/projects/13732725/todos/355530233

**Comment by njohner** [comment]
After reading the user input above, it seems to me it might make sense to have an updating mechanism for documents that are a pdf from another document. Otherwise they might need to generate a new "copy" of the pdf document when the source document gets updated.

For now I'd propose to add a marker interface on such documents, and maybe add the UUID of the source document in its annotations, or maybe in a behavior? That way it will make it easier if we have to flesh that out later...
