### ISSUE TITLE
Refactor `getTerm` when Solr is used

### ISSUE THREAD

**Issue by tarnap** [4teamwork/opengever.core#4246]
With #4243 a `solr_doc` is passed to the `getTerm` method

``` diff
-    def getTerm(self, value, brain=None):
+    def getTerm(self, value=None, brain=None, solr_doc=None):
```

Use Actor lookup also for Solr results

**Comment by lukasgraf** [comment]
I've looked into this, and came to the conclusion that refactoring this ([`UsersContactsInboxesSource.getTerm()`](https://github.com/4teamwork/opengever.core/blob/66d9706a9ad977e17c83917e7654f0ea1be8ee0e/opengever/ogds/base/sources.py#L355-L393) and [`AllEmailContactsAndUsersSource.getTerm()`](https://github.com/4teamwork/opengever.core/blob/66d9706a9ad977e17c83917e7654f0ea1be8ee0e/opengever/ogds/base/sources.py#L588-L618)) is harder than we thought, and doesn't result in much value at this time.

There's a couple reasons for this:
- The Actor pattern wouldn't help a whole lot here. In the case of the `AllEmailContactsAndUsersSource`, we want to yield individual terms for all the email addresses. That doesn't map well to an Actor (with with multiple addresses, there's still one Actor).
- The real complexity of these methods comes from the fact that they take contentish objects (brains, objects, solr documents) because they need to construct **term titles** that require info that can't be derived from the token alone, and otherwise would need repeated expensive lookups (catalog or SQL queries).
- On the other hand, for validation a simple containment check (`if token in source`) will cause a `source.getTerm(token)` which doesn't have and doesn't need all the info to build pretty, human readable titles. That's why `getTerm()`'s signature is so overloaded, and that's where a lot of the messiness stems from. The fact that Solr is also in the mix doesn't really make it that much worse.

The use of `IContentListingObject`s could possibly clean things up a bit. But also not that much, because we don't yet have `IContentListingObject` adapters for SQL yet.

Moving to `2019.1` for now.

**Comment by deiferni** [comment]
taking the liberty to close as per analysis not much value.
