### ISSUE TITLE
Ordnungsposition hat unter "Aktionen" 2x löschen (2018.3 Dev)

### ISSUE THREAD

**Issue by Linuexone** [4teamwork/opengever.core#4334]
Beim Human Testing Release 2018.3 wurde ein Fehler entdeckt.

Beschreibung:
Auf 3ter Stufe im Ordnungssystem, hat eine Ordnungsposition unter "Aktionen" 2x löschen vorhanden.

Plattform: DEV
Benutzer:  Gever Administrator
Beispielfall: https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/kommissionen-mit-selbstaendigen-verwaltungsbefugnissen/kommission-fuer-rechtsfragen/allgemeines#dossiers

Siehe Screenshot

![zweimal loschen vorhanden](https://user-images.githubusercontent.com/5165030/40364047-919d18c2-5dd1-11e8-9dad-7253cca7d6e1.png)
![release2018 3op](https://user-images.githubusercontent.com/5165030/40364065-9b4057ea-5dd1-11e8-8d1c-a7c8924cc57d.png)

**Comment by njohner** [comment]
There are 2 different `delete` buttons in play here. One comes from plone and is available everywhere. The other one, is the one mentioned by @deiferni above, which is only available if the `RepositoryFolder` is empty.

**Comment by deiferni** [comment]
Ich vermute die Änderung ist in https://github.com/4teamwork/opengever.core/pull/3598/ entstanden.

**Comment by njohner** [comment]
Indeed since #3598, which was meant to allow deletion of private folders, the delete button is available everywhere where the user has "Delete permission".
This is apparent in the above PR, where the delete button had to be added in several tests:
https://github.com/4teamwork/opengever.core/pull/3598/files#diff-c49b1433ed974e1c903d02886cbdadcfR133
https://github.com/4teamwork/opengever.core/pull/3598/files#diff-d346daf314a6065162142af1bbfd6967R117

Discussion with @deiferni led to the conclusion to restrict the availability of the button only to private folders (which seems to be what was intended in #3598). I implemented this in https://github.com/4teamwork/opengever.core/tree/nj_delete

But since then the availability of `Delete button` has been made use of in at least one commit: 
https://github.com/4teamwork/opengever.core/commit/ead82e4cbb60ca287a01710d8fcd394a3cdcc56a
So I'd propose to make a view `is_delete_available_on_object`, which would for now return `True` for `PrivateFolder` and `TaskTemplate` and nothing else. It would then be easy to keep control over where the button is available.
