### ISSUE TITLE
Imported content from eCH-0147 messages has values of wrong type

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#4376]
It seems that textline fields are assigned a more specific XML type instead of a Python unicode string during eCH-0147 import.

In plone.restapi serialization this results in an error like this:
```
2018-05-29 15:51:20 ERROR Zope.SiteErrorLog 1527601880.970.295844106497 http://localhost:8081/fd/ordnungssystem/ressourcen-und-support/ict/allgemeines/dossier-2039/document-1098/GET_application_json_
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.rest.service, line 23, in __call__
  Module plone.restapi.services, line 19, in render
  Module plone.restapi.services.content.get, line 19, in reply
  Module opengever.api.document, line 19, in __call__
  Module plone.restapi.serializer.dxcontent, line 84, in __call__
  Module plone.restapi.serializer.dxfields, line 76, in __call__
  Module plone.restapi.serializer.converters, line 42, in json_compatible
  Module zope.component.hooks, line 104, in adapter_hook
  Module plone.restapi.serializer.converters, line 103, in dict_converter
  Module plone.restapi.serializer.converters, line 42, in json_compatible
  Module zope.component.hooks, line 104, in adapter_hook
  Module plone.restapi.serializer.converters, line 56, in default_converter
TypeError: No converter for making u'application/pdf' (<class 'pyxb.binding.datatypes.token'>) JSON compatible.
```

We should always store the correct type defined by the field type.

**Comment by Rotonen** [comment]
All strings, booleans etc. (all non-dates) are broken from eCH-0147 imports.

The import is pending an once-over and we need to hunt through all client data which might have been impacted out there.

https://github.com/pabigot/pyxb/blob/14737c23a125fd12c954823ad64fc4497816fae3/pyxb/binding/datatypes.py#L60-L62

**Comment by lukasgraf** [comment]
Regarding running an upgrade step as **selectively** as possible:

Objects that have been created via an OGGBundle import can be recognized because they have an `oggbundle_guid` in their annotations - this is the GUID from the bundle that [gets set during object construction](https://github.com/4teamwork/opengever.core/blob/master/opengever/bundle/sections/constructor.py#L98-L102). There's also a [corresponding `bundle_guid` index](https://github.com/4teamwork/opengever.core/blob/master/opengever/bundle/console.py#L82-L98) that gets created on bundle import [(indexer is here)](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/indexes.py#L30-L37), and should still exist if it hasn't been manually removed.

So in those cases it should be possible to vastly reduce the set of objects that need to be checked.

**Comment by deiferni** [comment]
I have reverted this issue. The upgrade does not work @phgross @Rotonen.
