### ISSUE TITLE
OGIP 36: Ergänzung Benachrichtigungseinstellungen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4414]
Die Benachrichtigungseinstellungen sollen um die neuen Arten von Benachrichtigung ergänzt werden.
Die in https://github.com/4teamwork/opengever.core/issues/4413 erfassten defaults sollen vom Benutzer übersteuert werden können.

Die Aktionen `Eingereichter Antrag kommentiert` und `Antrag kommentiert` sollen zusammengefasst werden.

Die Benachrichtigungseinstellungen werden langsam etwas gross. Denkbar wäre eine Unterteilung mittels Tabs, oder zumindest die Einstellungen für Aufgaben und Anträge durch whitespace etwas voneinander zu Trennen.
<img width="900" alt="screen shot 2018-06-06 at 14 37 25" src="https://user-images.githubusercontent.com/736583/41038663-468444ce-6997-11e8-8d65-80a7f693ed32.png">

Harvest: _`Feature: Benachrichtigung SPV - OGIP 36`_

**Comment by deiferni** [comment]
There seem to be issues with the changes, see https://sentry.4teamwork.ch/sentry/onegov-gever/issues/4732/

**Comment by deiferni** [comment]
@elioschmutz please have a look

**Comment by elioschmutz** [comment]
This is an issue introduced with PR: https://github.com/4teamwork/opengever.core/pull/4367

An upgradestep for adding the new activities into the `notification_defaults` table is missing.

@deiferni I'll close this issue again because it's not related to this issue or the OGIP36

@njohner could you please add the missing upgradestep (i.e. https://github.com/4teamwork/opengever.core/blob/master/opengever/core/upgrades/20180620155648_add_meeting_notification_settings/upgrade.py) for the new activities:

- `task-transition-skipped-open`
- `task-transition-rejected-skipped`
- `task-transition-planned-skipped`

**Comment by deiferni** [comment]
thanks for investigating 💛 👍
