### ISSUE TITLE
Cleanup leftovers from non-word meetings

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#4455]
- In "meeting.js" there are some leftovers from non-word meetings, namely everything associated with the event click on `.edit-document`

**Comment by deiferni** [comment]
Ergänzt mit `Pin.js` issue aus https://github.com/4teamwork/opengever.core/pull/4443.

**Comment by deiferni** [comment]
@njohner i think the `.edit-document` functionality is relevant for this button
![screen shot 2018-06-18 at 16 32 36](https://user-images.githubusercontent.com/736583/41542497-645640b0-7315-11e8-839f-1e55b508839e.png)
i would not remove those events 😂.

could it be you copied the wrong class name? any chance you might remember the correct one? otherwise i'll close.

**Comment by njohner** [comment]
Right... I guess I meant `edit-agenda-item`. This seems to have been droped in https://github.com/4teamwork/opengever.core/pull/4397
