### ISSUE TITLE
TaskReminder doesn't properly sync to SQL

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4945]
I looked into this because `opengever.core:master` tests are [currently failing](https://ci.4teamwork.ch/builds/193805/tasks/317231) via `test_recalculate_remind_on_for_set_reminders_if_deadline_changed`.

It looks like it's not necessarily an issue with the tests, but the implementation is actually broken.

As discussed with @phgross, the `TaskReminder` data should
- use Plone, and only Plone, as the canonical source of truth to store data
- and only get synced to SQL for **indexing** purposes, via the [`SQLSyncer`](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/sqlsyncer.py#L12).

I think there's at least three issues with this:
- Reminder [gets recalculated before task's updated deadline is synced to SQL](https://github.com/4teamwork/opengever.core/blob/master/opengever/task/deadline_modifier.py#L65)
- Recalculating reminder [uses SQL as the source of truth, instead of Plone](https://github.com/4teamwork/opengever.core/blob/master/opengever/globalindex/model/reminder_settings.py#L40-L42) (for both the reminder data and the task deadline)
- Recalculating reminder only ever updates SQL, it seems that the [data in Plone object annotations only ever gets set on initial reminder creation](https://github.com/4teamwork/opengever.core/blob/master/opengever/task/reminder/reminder.py#L31).

**Comment by elioschmutz** [comment]
=> Side-Info about the last point 

> Recalculating reminder only ever updates SQL, it seems that the data in Plone object annotations only ever gets set on initial reminder creation.

- The current implementation does not need to recalculate the reminder in annotations after updating the duedate. Only the [relative option (yesterday, one_week_before...) is stored in annotations](https://github.com/4teamwork/opengever.core/blob/master/opengever/task/reminder/reminder.py#L81).
- But we need to update the SQL because the [effective reminder-date, based on the duedate and the option ,is stored in the SQL](https://github.com/4teamwork/opengever.core/blob/master/opengever/task/reminder/reminder.py#L90).

**Comment by phgross** [comment]
Closed via #4937
