### ISSUE TITLE
Provide bumblebee checksum in API.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5009]
A client application would like to know the bumblebee checksum of documents/mails. The checksum should be available for the object details and the `@listing` endpoint.

Might be possible to implement for all `IBumblebeeable`s.

Could be solved together with https://github.com/4teamwork/opengever.core/issues/4979.

**Comment by elioschmutz** [comment]
To add the `checksums` and the `relative_path` (#4979) I'll need to add a `GeverSerializeToJson` and a `GeverSerializeFolderToJson` base classes inheriting from the plone.restapi serialize classes. This classes allows us to push global attributes (i.e. the `relative_path`) or interface specific attributes (i.e. the `checksum`).

Otherwise I have to hook in into several serializers to extend the serializers.

Is this the desired way to implement? Or do you have another strategy?

@phgross @deiferni

**Comment by lukasgraf** [comment]
@elioschmutz yes, it's unavoidable to bring some of the inheritance hierarchy from `plone.restapi`'s serializers over to GEVER - that's the way to go 👍
