### ISSUE TITLE
Aussonderung: Anbindung Austauschplattform

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5167]
_Harvest: `Projekt - GEVER SG, Optimierungen aus Pilotprojekt, Release 1.1` - `Entwicklung`_

Die Speicherung des SIP Packages als blob wurde bereits im Branch `pg_disposition_store` umgesetzt. 

Tasks:
- [x] `pg_disposition_store` PR erstellen, reviewen
- [x] add initial content for local development
- [x] FTP Test Share von Betrieb zur Verfügung stellen lassen (https://extranet.4teamwork.ch/betrieb/tracker/889)
- [x] Status Transport in Angebot führen und darstellen
- [x] Delivery via filesystem abschliessen (#5850)
- [x] Have OPS create a FTPS test-setup on our `dev` (see https://extranet.4teamwork.ch/betrieb/tracker/891/view):
  - [x] Install `vsftpd`, and [configure it in implcit SSL mode](https://serverfault.com/questions/65002/vsftpd-and-implicit-ssl) (`implicit_ssl=YES`)
  - [x] Set up an appropriate user
  - [x] ~Mount an FTPS connection to that server as a share on `dev` using [CurlFtpFS](http://curlftpfs.sourceforge.net/)~
- [x] ~Have OPS mount the FTPS connection to the _real_ share on the 805 test server~

**Comment by phgross** [comment]
Kleines Konzept: https://gever.4teamwork.ch/ordnungssystem/3/2/produkt-onegov-gever-aussonderung/dossier-3324/document-29733?SearchableText=austauschplattform#overview

@deiferni hast du noch Einwände oder Vorschläge?

**Comment by deiferni** [comment]
Kleinere Korrekturen/Anmerkungen auch direkt im Word im Änderungsmodus. Der wichtigste Punkt:  ich würde die SIP-Dateien nicht direkt und selber auf dem Filesystem speichern, sondern analog zu https://github.com/4teamwork/opengever.core/pull/4954 als blob.

**Comment by deiferni** [comment]
the share should be available as per https://extranet.4teamwork.ch/betrieb/tracker/889

**Comment by deiferni** [comment]
Unassigning `self`. Current state:
- https://github.com/4teamwork/opengever.core/pull/5837 might need to be merged/fixed 
- https://github.com/4teamwork/opengever.core/pull/5840 will help with local development
Have not started with other tasks, so any of those can be taken over.

**Comment by lukasgraf** [comment]
I started continuing this (got some proof-of-concept code for an SFTP client (for delivery) and a stub SFTP server (for use in tests).

I stopped work on this however, because I've got serious doubts about whether it's actually an SFTP share that the customer is running. The hostname is `ftps.example.org`, which strongly  indicates that they're actually using [FTPS](https://en.wikipedia.org/wiki/FTPS) (FTP over SSL), not [SFTP](https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol) (SSH File Transfer Protocol). In order not to build something we don't actually need, I'm waiting on further clarification on this.

**Comment by lukasgraf** [comment]
It is indeed FTPS (just confirmed with customer).
Aparently, FTPS support in Python is mediocre at best. See https://pypi.org/project/ftps/ and the referenced bugs for example. Yay 😢

**Comment by lukasgraf** [comment]
The current state of this is that I will implent the things around the actual transport for now.
In order to still be able to test this, I wil implement a dead simple `FilesystemTransport`, that just copies the SIP to a specified directory on a filesystem.

Potentially, this could even be used in production to enable FTPS transport:
Using http://curlftpfs.sourceforge.net/ we could set up the FTPS connection, and just mount it as a FUSE filesystem, that GEVER doesn't need to know about (as long as the abstraction holds).

**Comment by lukasgraf** [comment]
Created follow up issue for ECH actions:
https://github.com/4teamwork/opengever.core/issues/5886

**Comment by phgross** [comment]
Das Testing in der Kundenumgebung ist abhängig von https://github.com/4teamwork/ris/issues/1599 und kann deshalb noch nicht gemacht werden. Aus meiner Sicht aber alles i.o.
