### ISSUE TITLE
Enable solr for local development by default

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5168]
We're going to enable solr on all our productive deployments in the future, so it makes sense to develop and test on a solr enabled GEVER.

**Comment by lukasgraf** [comment]
What's our plan here on how to start Solr during local development?

Having to start Solr in a second tab all the time gets old really quick. It's also quite error prone in terms of mixing the wrong Solr core and Zope instance combination, which could have very weird effects.

Not starting it isn't really an option for many things, because TabbedView listings also need Solr.

@Rotonen suggested to possibly use supervisor for local development as well. Which wouldn't be a bad thing anyway (closer to production), but how would we
- prevent `supervisord` from detaching immediately, to ensure the `bin/instance` stdout goes to the terminal
- get it to properly set up an interactive terminal, so you can still use `pdb`

@Rotonen I believe you mentioned some kind of support for this in supervisor - could you drop a pointer here as to what exactly you were thinking of?

**Comment by Rotonen** [comment]
There is indeed a flag for that, used widely by containers for running multiple closely coupled things in the same container.

`-n, --nodaemon | Run supervisord in the foreground.`

Can also be set in the main config file:

```
[supervisord]
nodaemon=true
```

Additionally the log outputs can be redirected per process.

```
[instance0]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
```

Anything other than the instance itself should probably log to disk to keep the output simple.

**Comment by lukasgraf** [comment]
@Rotonen thanks - but as discussed, that still leaves the issue with `pdb`.

The *"start everything else using supervisord, but `bin/instance fg` manually"* approach could work though. Eventually.

For now, as discussed with @njohner, we'll try whether we can make an approach work where a shell wrapper script essentially just does

```bash
bin/solr start
bin/instance fg
bin/solr stop
```

**Comment by lukasgraf** [comment]
Additionally, we should be able to roll this out in phases:
- Phase 1: Just *provide* Solr for local development, so it's there when wanted, but would still need to be activated using the `activate_solr.py` script. No Solr requirement for local development by default yet
- Phase 2: Enable the `use_solr` registry flag for local development (therefore actively requiring Solr), and drop the `SearchableText` index during GEVER Setup *for local development*
- Phase 3: Enable Solr for new production deployments by default (like above)
