### ISSUE TITLE
Wording Infotexte SPV Sitzungsabschluss verbessern

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5205]
Folgende Texte sollten korrigiert werden:

**Aktuell, Protokollauszug ablegen (Overlay):**
Der Protokollauszug wird an den Antragsteller bzw. ins Ursprungsdossier des Antrags zurückgesendet. Es können keine weiteren Protokollauszüge zurückgesendet werden.
Wollen Sie diesen Protokollauszug wirklich an den Antragsteller zurücksenden?
Protokollauszug ablegen Abbrechen

**Neu, Protokollauszug ablegen (Overlay):**
Der Protokollauszug wird im Antragsdossier abgelegt. Es können keine weiteren Protokollauszüge abgelegt werden.
Wollen Sie diesen Protokollauszug wirklich im Antragsdossier ablegen?
Protokollauszug ablegen / Abbrechen
 
**Aktuell Sitzung abschliessen (inaktiv):**
Die Sitzung kann erst abgeschlossen werden wenn alle Traktanden abgeschlossen sind und die Protokollauszüge generiert und zurückgesendet wurden.

**Neu Sitzung abschliessen (inaktiv):**
Die Sitzung kann erst abgeschlossen werden, wenn bei allen eingereichten Anträgen die Protokollauszüge abgelegt sind.

**Comment by njohner** [comment]
This was already modified in a previous release. Currently we have:

**Protokollauszug ablegen (Overlay):**
Der Protokollauszug wird im Ursprungsdossier des Antrags abgelegt. Es können keine weiteren Protokollauszüge abgelegt werden.
Wollen Sie diesen Protokollauszug wirklich im Ursprungsdossier ablegen?

So the difference here is using `Ursprungsdossier` instead of `Antragsdossier`. Should that be corrected? `Antragsdossier` is used in only one place in the whole GEVER for now...
