### ISSUE TITLE
Test server self test runs get stuck if XMLRPC port allocation fails

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#5331]
https://ci.4teamwork.ch/builds/220341/tasks/362106

How do we allocate that port?

**Comment by deiferni** [comment]
@jone can we have a look at this tomorrow. a quick temporary fix would also be welcome, maybe an elegantly placed `@skip` somewhere 😉.

**Comment by jone** [comment]
Sorry for the trouble. I'll look into it.
My suspicion is that Jenkins' port allocator plugin does not play well with the Jenkins slave: the ports are probably allocated on master but used on the slave, so collisions cannot be avoided.

- Using port `0` does not really work because the selftest script starts the server in a subprocess but needs to know the port for connecting to.
- Using port `0` and printing the port would probably involve patching `plone.app.robotframework` or rewriting parts of it, I'd like to avoid that.
- Using a path based socket does not work with testbrowser, I guess.
- Looking into Jenkins is probably the best approach.

**Comment by Rotonen** [comment]
@jone yes, this is the reason why I made logic in `plone.testing` for letting the operating system allocate a free port for the socket.

Monkey patch `plone.app.robotframework` to also parse the xmlrpc port off the test layer and store the port there on the layer setup.
