### ISSUE TITLE
@vocabularies/lifecycle_retention_period_vocabulary returns string instead of integer

### ISSUE THREAD

**Issue by all4manu** [4teamwork/opengever.core#5412]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

The endpoint returns the tokens `5, 10, 15, 20, 25` as strings. However when creating a new dossier for instance, integers are required. Please change this @vocabularies endpoint to return its tokens as integers.

**Comment by Rotonen** [comment]
Dug things out a bit, and do we want to change this at the very root of the interface schema, or just tackle the output side?

It'd seem we've been paving over this in layers over the years:
https://github.com/4teamwork/opengever.core/pull/2978

**Comment by lukasgraf** [comment]
@rotone I'd say fix it for good.

Casting to `int` for `retention_period` values happens here: https://github.com/4teamwork/opengever.core/blob/master/opengever/base/behaviors/lifecycle.py#L112-L125 (unconditionally, without any expectation of this every failing). So IMHO it's a safe assumption that there are always integers.

Because this is only done when retention periods are restricted (which is feature flagged), I'm assuming the other code path without this `RestrictedVocabularyFactory` in play is what leads to them getting stored as strings.

The value type of the registry record could therefore be changed to `Int` as well (with the according upgrade step that migrates the registry records obviously).

**Comment by deiferni** [comment]
I agree 👍. Please do provide an estimate though.

**Comment by Rotonen** [comment]
This has boiled down to `plone.restapi` never providing the values in the `GET` endpoint for vocabularies.

The titles and terms are returned as strings as they should be.

https://github.com/plone/plone.restapi/blob/6758f1db91f378cf00a7a58e06d8421cea2d958b/src/plone/restapi/serializer/vocabularies.py#L46-L50

I'll make a PR upstream. Hopefully we can get that landed before the batching one lands.

**Comment by Rotonen** [comment]
As vocabularies can contain things like `MemberData` objects or images as values, what needs to happen is to move the input side is to add a `token -> value` lookup for all vocabulary backed field types.

The frontend can and should just use the tokens, as it currently does.

We'll tackle this upstream at a later point. As this might have many close cousins throughout `plone.restapi`, I've removed the estimate for now.

**Comment by Rotonen** [comment]
Seems @buchi fixed this upstream:

https://github.com/plone/plone.restapi/pull/692

**Comment by phgross** [comment]
https://github.com/plone/plone.restapi/pull/692 is part of the new plone.restapi version (see #5725)
