### ISSUE TITLE
Dossier transition views do no prevent invalid transitions

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5638]
_Harvest: `OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

Steps to reproduce:
* go to an inactive dossier
* add the `transition-resolve` to the url
* you get redirected to the dossier with a message saying that the transition succeeded

You can do the same with other transitions, for example reactivate an inactive dossier.

**Comment by lukasgraf** [comment]
@njohner I just looked into this "by accident", because that's a behavior I also noticed and wanted to have a closer look.

From what I can tell, it's mostly a confusing message - the transition is not actually performed.

The underlying reason, at least in the case of resolving dossiers, is that we need to have [a condition](https://github.com/4teamwork/opengever.core/blob/965c059674b6ce6926fb422c07fb8ca8d8573194/opengever/dossier/resolve.py#L343-L345) that silently skips already resolved **sub**dossiers - because those could exist in an already resolved state, and that's ok and to be expected.

If that condition is disabled, the workflow tool will successfully prevent the transition for already resolved dossiers by raising `WorkflowException: No workflow provides the '${action_id}' action.`.

**Comment by njohner** [comment]
Yes I'd also seen that it comes from there. And there is a similar handling for dossier reactivation.
Basically this is not really a problem, as I don't think there is any realistic scenario where we would end up performing the transitions on some subdossiers but not on the main dossier. For this we would need some states that actually don't happen, like the main dossier resolved and some subdossiers still open.
Still, we should handle the case where the transition cannot be executed on the main dossier and return an error in that case.
