### ISSUE TITLE
Users vocabulary contains multiple items for some of the users.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5647]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

The `plone.app.vocabularies.Users` vocabulary, called via API `@vocabularies/plone.app.vocabularies.Users` returns for some of the users in our dev LDAP multiple vocabulary items. Examples: `philippe.gross`

A further look in to the vocabulary showed that the acl_users.searchUsers returns the `mutable_properties` from the `Products.PlonePAS.plugins.property.ZODBMutablePropertyProvider` plugin as well as the normal entries.

**Comment by Rotonen** [comment]
Not currently able to bump `plone.restapi` to the latest version as it has issues in regards to serializing some of the vocabularies.

Some potentially salvageable upstream work can be found in https://github.com/plone/plone.restapi/pull/744, but that is currently blocked by the tests not working on 5.1.

**Comment by lukasgraf** [comment]
Closing, because:
Using the `plone.app.vocabularies.Users` vocabulary as a basis for the `responsible` field is incorrect anyway. Instead, the `AssignedUsersSourceBinder` should be used, as [indicated on the schema field](https://github.com/4teamwork/opengever.core/blob/19b757c21f64e3d6eaa7824e9f03be0b9d80e3b0/opengever/dossier/behaviors/dossier.py#L90).
