### ISSUE TITLE
Checksumme fehlt in Solr

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#5828]
Version: 2019.4.0.dev0

Neues Dokument per Drag'n'drop hochgeladen:
https://dev.onegovgever.ch/rk/ordnungssystem/ressourcen-und-support/ict/informatik/software-fachapplikationen/dossier-52/document-1382#overview

Dokument über `@listing`-Endpoint abgefragt:
https://dev.onegovgever.ch/rk/ordnungssystem/ressourcen-und-support/ict/informatik/software-fachapplikationen/dossier-52/@listing?columns%3Alist=bumblebee_checksum&name=documents

Resultat:
```
{
  "@id": "https://dev.onegovgever.ch/rk/ordnungssystem/ressourcen-und-support/ict/informatik/software-fachapplikationen/dossier-52/@listing?columns%3Alist=bumblebee_checksum&name=documents", 
  "b_size": 25, 
  "b_start": 0, 
  "items": [
    {
      "@id": "https://dev.onegovgever.ch/rk/ordnungssystem/ressourcen-und-support/ict/informatik/software-fachapplikationen/dossier-52/document-1382", 
      "bumblebee_checksum": null
    }
  ], 
  "items_total": 1
}
```

Problem: `bumblebee_checksum` ist `null`
Erwartet: korrekte Checksumme

Über API-Request direkt auf das Dokument wird die Checksumme ausgeliefert:
https://dev.onegovgever.ch/rk/ordnungssystem/ressourcen-und-support/ict/informatik/software-fachapplikationen/dossier-52/document-1382

```
...
"bumblebee_checksum": "576a898421514a04cd9f31245dccdd87c94819772b2578e19cd4d7b11c894795",
```

Nebenbemerkung:
Das gleiche Problem habe ich im Testserver mit #5804 festgestellt.

**Comment by lukasgraf** [comment]
This is happening because
- `ftw.bumblebee` uses the "use a cheap index to only update metadata" trick to update the `bumblebee_checksum` column: [`reindexObject(idxs=["getId"])`](https://github.com/4teamwork/ftw.bumblebee/blob/9ef7f36efb95a2ce82ae5ae5ca2cfb5ec339153a/ftw/bumblebee/document.py#L71)
- `ftw.solr`, if a list of `attributes` (indexes) is passed, [assumes it should do an atomic update](https://github.com/4teamwork/ftw.solr/blob/50d3345663c00b7aa2b2739069d441c575945ef4/ftw/solr/handlers.py#L49-L50)
- This causes metadata to not be updated, only the specified indexes.

At this point I'm not 100% sure yet because this happens only because `getId` is not in our Solr-Schema, and therefore gets removed from the `attributes` (leading to an empty list), or if it's actually the case that metadata in Solr NEVER gets updated as soon as `idxs` is specified in a `reindexObject()` call. But I suspect the latter is the case unfortunately.

**Comment by lukasgraf** [comment]
Issue in `ftw.solr`: 4teamwork/ftw.solr#136

**Comment by lukasgraf** [comment]
Second, related issue: 4teamwork/ftw.solr#137
(This issue would become a problem once we somehow manage to solve the first one).

**Comment by lukasgraf** [comment]
Moved issue back to backlog because we need to discuss and address the two `ftw.solr` issues mentioned above first.
