### ISSUE TITLE
Modification dates in recently touched menu are not uniform

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5887]
We have a discrepancy between the `last_touched` date for recently touched vs checked out documents. In one case it's timezone aware and in the other it's not. There is potential for a shift between the two when displayed together (I think the timezone naive is actually in the current local timezone). 

See comments in https://github.com/4teamwork/opengever.core/pull/5880

Todos:
 - [ ] Analyse
 - [ ] Anpassen der Serialisierung
 - [ ] evtl. Migration/Upgradestep

**Comment by phgross** [comment]
The difference between the checked_out documents and the recently touched documents, is because the recently_touched list stores its own timestamp as datetime object, without timezone information, but for the checked_out documents list, the modified attribute from the brain is used, which is an timezone aware zope DateTime object.
