### ISSUE TITLE
Use plone.protect 3.x in order to get automatic CSRF protection

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#754]
In order to get automatic CSRF protection for all our forms, we would need to use at least version 3.x of [`plone.protect`](https://github.com/plone/plone.protect).

`plone.protect` 2.x provides all the necessary primitives to implement CSRF protection yourself (by having a CSRF token generated, inserting it into the form and validating it in the view), but it does not yet patch any of the CRUD z3c forms.

`plone.protect` in Version 3.x however should do that, [according to the docs](https://github.com/plone/plone.protect/#automatic-csrf-protection). `plone.protect` 3.0 is what Plone 5 is supposed to be using, but at first glance it seems it should work just fine with Plone 4.x - pinning `plone.protect == 3.0.1` and `plone.keyring == 3.0.0` is all that's required to at least satisfy the version requirements:

```ini
[versions]
plone.protect = 3.0.1
plone.keyring = 3.0.0
```

However, in GEVER there is an issue where on some views, this confirmation dialog is shown:

![csrf_confirmation](https://cloud.githubusercontent.com/assets/405124/6185993/6a904e58-b374-11e4-9d13-0d910878fe7b.png)

This happens for example for the @@personal_overview, but also for most tabbed_views as far as I can tell. This dialog is caused by some code in [`plone.protect.auto.ProtectTransform._check()`](https://github.com/plone/plone.protect/blob/master/plone/protect/auto.py#L183-L189), but I haven't investigated the exact reason(s) in detail yet.

The things I'm currently suspecting to be causing, or at least be related to this problem, are:

- Redirects (301, 302)
- Writes on display
- Database modifications in GET requests

While we need to address these points in order for `plone.protect` to work properly, they aren't cool anyway and should be fixed. Redirects aren't necessary evil, but they should be used sparingly because they also affect performance (doubling round-trip time and making caching more difficult).

---

**TODO**: Provide actual examples where CSRF currently is possible in GEVER.

I don't have any concrete examples yet, but I'll construct one later in order to reproduce a case of CSRF and later verify that it's actually fixed. For now, this is how it would work on a conceptual level:

- Send an HTML email to a user you know to be currently logged into GEVER

#### `GET` requests

- Include an `<img />` element in the mail's HTML with a `src` of `http://gever/context/delete_this_thing`

#### `POST` requests
 
- Include a `<form />` in the mail's HTML with a submit button `Claim your 10'000$ prize now!` and the form's `action` pointing to `http://gever/context/delete_this_thing_post_only`. The necessary `POST` parameters would be included in the form as hidden fields.

**Comment by jone** [comment]
**1. Session**
Accessing the session makes persistent changes, resulting in a DB write, making CSRF auto protection trigger and present the confirmation page.
The [redirector viewlet](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/redirector.py#L26) accesses the session whenever the above-content-title viewlet is rendered.

**2. Locking**
When "Edit" is clicked on any object, the locking behavior (when enabled) makes a write to lock the object. Since the "Edit" request is GET, CSRF auto protection triggers.

--

For `plone.protect 3` to work properly with non-vanilla Plone there must be a way to whitelist objects. This is not that easy since the objects may have children.

There also should be an easier way to investigate which objects caused the problems. Currently nothing is logged at all, but having empty BTrees and strange Increasers does not help much :confused:
