### ISSUE TITLE
SchemaMigration and PostgreSQL - DDL statements not executed

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#766]
It seems that DDL statements are not always committed when executing upgrades on a database with transactional ddl, i.e. PostgreSQL.

**Comment by lukasgraf** [comment]
The issue here is that with PostgreSQL and transactional DDL enabled, the SQLAlchemy transaction doesn't get committed (even when doing an explicit `transaction.commit()` on the `zope.sqlalchemy` transaction manager) if the transaction **only** contains DDL statements.

As soon as any DML statement is added to the transaction (e.g. an `INSERT`) the transaction is considered dirty and both DDL and DML statements will be committed.

**Comment by lukasgraf** [comment]
Apparently this is by design:

> By default, zope.sqlalchemy puts sessions in an 'active' state when they are
> first used. ORM write operations automatically move the session into a
> 'changed' state. This avoids unnecessary database commits. Sometimes it
> is necessary to interact with the database directly through SQL. It is not
> possible to guess whether such an operation is a read or a write. Therefore we
> must manually mark the session as changed when manual SQL statements write
> to the DB.

(From [`zope/sqlalchemy/README.txt`](https://github.com/zopefoundation/zope.sqlalchemy/blob/master/src/zope/sqlalchemy/README.txt#L145-L167))

Flagging the session as changed using `mark_changed(session)` does the trick.

**Comment by deiferni** [comment]
this has been fixed :sunglasses:
